// All recipes live here, in the same order as the book.
// A recipe with only slug/title/section/colour shows as "coming soon" in the index.
// Fields: intro, serves, oven and time are optional; ingredients and method make it a full page.
// `notes` are extra boxes shown under the ingredients: { title, items: [...] }.
// `image` is optional: if the file is missing, an illustrated placeholder is shown.
window.RECIPES = [
  {
    slug: "zhahlas-chai",
    title: "Zhahla’s Chai",
    section: "chai",
    colour: "#A0522D",
    intro:
      "This comforting, well spiced and seasoned drink will make you turn your nose away from chai at your local cafe. Like a hug in a mug I love making this chai for others and have found my friends become extremely excited when they find out that I am making this. Perfect paired with cake rusk (a dehydrated cake biscuit) you will find in most South and Central Asian supermarkets. There are a lot of chai recipes out there and variations of this recipe you can follow so feel free to make this recipe your own.",
    serves: "Six or seven people",
    oven: "Hob",
    time: "10 min rolling boil",
    ingredients: [
      "800ml milk (cows milk or plant based such as oat)",
      "800ml water",
      "6/7 cardamom pods",
      "4 half barks of cinnamon sticks",
      "1 star anise (optional)",
      "Small handful of fennel seeds",
      "Fresh ginger (optional)",
      "Clove (optional)",
      "5 teabags (decaf or normal)",
    ],
    notes: [
      {
        title: "Using a chai masala",
        items: [
          "Alternatively if you have a blended chai mix (a chai masala) you would be able to skip the toasting step and boil your water then add the chai masala.",
        ],
      },
    ],
    method: [
      "Boil a kettle with the water that you need for the chai (you might need to do this multiple times if you are making a lot of chai).",
      "Toast all your spices (cardamom pods, cinnamon stick, star anise, fennel seeds and cloves) at the bottom of your pan until their aroma releases. The fennel seeds burn easily so keep an eye on your spices as they heat up and feel free to mix them around a little. Once the spices are ready, lower the heat and let the pan cool down. Once it has cooled down pour in the boiled water carefully. The saucepan might make a loud sizzle sound so gently pour a little boiled water in first before pouring in more.",
      "Add the teabags and let the mixture boil for two minutes.",
      "Add milk and bring to a rolling boil. Let it boil quite vigorously for ten minutes. The chai may foam up, in which case turn down the heat slightly, still letting it boil. Watch the pot carefully as it simmers, sometimes the chai will overflow out of the pot. If you see this about to happen turn the heat down. If not don’t worry. If the chai overflows that’s okay, just make sure you give your counter a wipe and continue to make your chai!",
      "Remove the pan from the heat and strain the chai into mugs or glasses. For a classic feel, serve the chai in glasses.",
    ],
  },

  {
    slug: "one-pot-chicken-pie",
    title: "One Pot Chicken Pie",
    image: "images/one-pot-chicken-pie.jpg",
    section: "mains",
    colour: "#B7853F",
    intro:
      "This recipe is great for meal prep or hosting others. On a cold autumn or winter evening, coming home and making this for yourself or for others is an ultimate form of self care. I love how the pie can all be made in one pan (if your pan is oven safe) and the sweet potato fries can be cut and also placed straight into a tray in the oven, resulting in minimum washing up.",
    serves: "Five people (one pie)",
    oven: "180C Fan / 200C / Gas Mark 6",
    time: "25–30 min bake",
    ingredients: [
      "500g chicken or Quorn chicken (diced)",
      "1tbsp oil",
      "Bag of frozen vegetables",
      "40g unsalted butter",
      "Chicken stock cube",
      "Ready made puff pastry",
      "1tsp paprika powder",
      "1 small onion",
      "3 cloves garlic",
      "350ml milk",
      "1 egg (whisked)",
      "Hot water",
      "30g flour (optional)",
      "Salt",
      "Pepper",
      "1tsp mixed herbs",
      "1 stock pot/cube",
      "1tsp red chilli flakes",
    ],
    method: [
      "Preheat the oven to 180C fan / 200C / Gas Mark 6.",
      "If possible use a pan that is oven safe for this recipe. If you don’t have a pan that is oven safe, you will need to pour the chicken pot pie filling into a baking dish that is oven safe, later on.",
      "Add oil to the pan and bring the pan to medium heat.",
      "Soften the onion and garlic in oil.",
      "Then add your diced chicken and spices and stock cube. Mix all together and allow this to cook.",
      "Once the chicken is cooked add flour and cook for 5 minutes.",
      "Then add in your milk and allow the mixture to thicken.",
      "Then add frozen veg.",
      "Taste and add any more seasoning if needed.",
      "Pour the pie mixture into an oven safe dish.",
      "Roll out your sheet of the puff pastry and cut into squares.",
      "Layer the squares on top of the pie mixture.",
      "Use a pastry brush or spoon to wash the dough with egg.",
      "Bake the pie for 25-30 minutes or until golden brown.",
    ],
  },
  {
    slug: "sweet-potato-fries",
    title: "Sweet Potato Fries",
    section: "mains",
    colour: "#C8733A",
    intro: "These are a great addition to have with any dish, especially the one pot pie.",
    serves: "Four people",
    time: "30 min in the oven",
    ingredients: [
      "1kg sweet potatoes",
      "Olive oil",
      "Seasonings for fries (optional)",
      "Semolina",
      "Plain flour",
      "Salt",
      "Pepper",
      "½ tsp garlic powder",
      "¼ tsp chilli powder",
      "½ tsp paprika",
      "1tbsp white granulated sugar",
      "½ tbsp brown sugar",
    ],
    method: [
      "Line a tray with baking paper.",
      "Peel the sweet potatoes, then cut into wedges.",
      "Put into your baking tray, spreading the sweet potatoes out as much as possible (this will help them cook and get slightly crispy).",
      "Then drizzle olive oil on top coating them in the oil. You might need to use multiple oven trays to make sure the sweet potatoes are spread out. At this stage if you have semolina you can sprinkle these on the sweet potatoes (the semolina absorbs the moisture from the fries, and adds some texture to the fries).",
      "Put in the oven for 30 minutes, flipping halfway through.",
      "Once cooked, season with salt, pepper and paprika on top.",
      "For the ultimate sweet potato fries also sprinkle paprika, garlic powder, chilli powder, both types of sugars.",
    ],
  },
  {
    slug: "french-chicken",
    title: "French Chicken",
    section: "mains",
    colour: "#9A7B3F",
    intro:
      "I tried this dish for the first time at a come dine with me at university. This dish feels sophisticated and delicious and the broth feels comforting and well spiced. This is what I would make if I wanted to impress someone or wanted a comforting meal. Serve with crusty bread rolls or some roasted vegetables.",
    serves: "Four people",
    oven: "150C / Gas Mark 2 / 170C Fan",
    time: "35–40 min in the oven",
    ingredients: [
      "4 chicken drumsticks/ thighs",
      "¼ onion, finely diced",
      "3 garlic cloves sliced",
      "2 tomatoes",
      "75ml dry white wine (optional)",
      "1tbsp rapeseed oil",
      "1tbsp rice wine vinegar",
      "½ tbsp dijon mustard",
      "1 sprig fresh tarragon",
      "3-4 sage leaves",
      "50ml water",
      "Handful parsley",
    ],
    method: [
      "Preheat the oven to 150C / Gas Mark 2 / 170C fan.",
      "Fry chicken on high heat in oil in casserole pan/ frying pan/ pot for 5 minutes until golden brown and season with salt and pepper.",
      "Remove chicken to plate and spoon out most of fat from casserole.",
      "Add garlic and onion and sweeten for 4-5 minutes but don’t let them colour.",
      "Add vinegar and boil for 10 seconds until vinegar reduced to a syrup.",
      "Add white wine and bring to a boil for a few seconds, whisk in mustard, tomatoes, tarragon, and sage. Pour in water and return chicken to pan.",
      "Bring to boil, cover with lid and transfer to oven and cook for 35-40 minutes (liquid shouldn’t boil but cook at a very low simmer with just 1-2 bubbles breaking the surface).",
      "Chicken will be juicy + tender. Check and season.",
      "Serve with parsley.",
    ],
  },
  {
    slug: "one-pot-beef-pasta",
    title: "One Pot Beef Pasta",
    section: "mains",
    colour: "#A4443A",
    intro:
      "Also a great recipe to have on hand, I love to whip this up when I want to meal prep but don’t have a lot of time on my hands. The pasta cooks in the beef broth here, saving you from cooking it separately in another pan. I add cherry tomatoes to bulk the dish out with slightly more veg, feel free to do the same if you’d like or skip the cherry tomatoes. If you are on a student budget feel free to skip the parmesan cheese.",
    serves: "Four to six people",
    oven: "Hob",
    time: "10–12 min simmer",
    ingredients: [
      "500g beef",
      "340g of conchiglie pasta (or other pasta)",
      "2 cups of milk",
      "Parmesan cheese (optional)",
      "1 to 2 beef stock cubes",
      "2tbsp oil",
      "1 onion, diced",
      "2 big handfuls of spinach",
      "Double cream",
      "Punnet of cherry tomatoes (optional)",
      "6 garlic cloves",
      "2tbsp tomato paste",
      "2tsp Italian seasoning",
      "1tsp paprika",
      "2tsp onion powder",
      "50ml of double cream (optional)",
      "½ tsp black pepper",
      "2tsp salt",
    ],
    method: [
      "Add oil to a pan at medium high heat and cook your onion and garlic until it starts to become a little golden.",
      "Then add your beef and spices. Break down the beef with your cooking utensil and cook until the beef has browned.",
      "Then add the cherry tomatoes and tomato paste. Cook for 5 minutes until the cherry tomatoes soften and the tomato paste darkens.",
      "Add the uncooked pasta, beef stock cube, water, milk, garlic powder, onion powder, Italian seasoning, and salt. Add in the amount of water your stock cube suggests. If this is not enough to cook the pasta you can add more water and another stock cube.",
      "Bring to a simmer, cover and cook for 10-12 minutes on medium - low heat. You might need to keep an eye on the pasta as its cooking time can vary.",
      "Stir in the cream and cook for a further two minutes.",
      "Stir in spinach and cook for another minute or two.",
      "Grate parmesan cheese over the top to serve.",
    ],
  },
  {
    slug: "moroccan-pastries",
    title: "Moroccan Pastries",
    section: "mains",
    colour: "#B8863B",
    intro: "These pastries aren’t too difficult to make and are a real showstopper.",
    serves: "Six people (six pastries)",
    oven: "220C (200C Fan) / Gas Mark 7",
    time: "20–25 min bake",
    ingredients: [
      "60g feta, crumbled",
      "Puff pastry sheet/shortcrust (320g ready rolled)",
      "1 egg beaten",
      "2tbsp pine nuts",
      "400g Swiss chard, stalks removed, leaves cut into strips 3cm wide",
      "2tbsp olive oil",
      "2tbsp flat leaf parsley, chopped",
      "1tbsp chopped fresh coriander",
      "1tbsp lemon juice",
      "2 garlic cloves peeled and crushed",
      "1tsp paprika",
      "½ tsp ground cumin",
      "¼ tsp salt, or more to taste",
    ],
    method: [
      "Preheat the oven to 220°C (200°C fan) / Gas Mark 7.",
      "To make the filling, heat the olive oil in a large saucepan over a medium-low heat. Add the Swiss chard and then stir in the remaining ingredients, except the feta and pine nuts. Cover the pan and cook for about 8 to 10 minutes until the chard is soft. Uncover the pan and cook for a further 5 minutes or until all the liquid has evaporated, stirring occasionally. Taste and adjust the seasoning, adding more salt if necessary. Remove the pan from the heat and stir in the feta and pine nuts. Leave the filling to cool to room temperature, when you can start assembling the hand pies.",
      "Alternatively, transfer the filling to a bowl, cover with clingfilm and refrigerate until ready to use; it will keep for up to 2 days.",
      "Unroll your pastry sheets on to a work surface and cut each sheet into squares or rectangles. Spoon about 4 tablespoons of the filling in the centre of each square/ rectangle. Fold one corner over the filling to meet the opposite corner to form a triangle or a rectangle, then seal the edges by pressing down with the tines of a fork.",
      "Place the turnovers on the lined baking tray, leaving about 2cm between them. Brush their tops with the beaten egg and bake for about 20 to 25 minutes until golden brown.",
      "Serve warm or at room temperature.",
    ],
  },
  {
    slug: "kadu-borani",
    title: "Kadu Borani",
    section: "mains",
    colour: "#C06A2E",
    intro:
      "An Afghan classic, this dish is heartwarming, with a strong butternut squash and tomato flavour. Served with yoghurt (seasoned to your liking), salad and a fluffy naan (or your choice of bread), this is perfect. I like to roast the squash in the oven but you can also cook the squash in the borani, adding it at the end and cooking for 20-25 minutes with water or in a frying pan before you make the sauce.",
    serves: "Four people",
    oven: "180C (for the squash)",
    time: "30 min roast, 20 min simmer",
    ingredients: [
      "1 butternut squash",
      "2 cans of chopped tomatoes",
      "1tbsp tomato paste",
      "Oil (vegetable or olive)",
      "2 cloves of garlic",
      "Yoghurt",
      "1tsp salt (or to taste)",
      "1tsp black pepper",
      "1tsp turmeric",
    ],
    method: [
      "Peel and slice the butternut squash into wedges and place on a lined tray, drizzle with oil and put into the oven (180C) for 30 minutes. Flip halfway through.",
      "While the butternut squash cooks, fry some garlic with tomato paste in a pot, until fragrant.",
      "Add your spices.",
      "Add the wedges of butternut squash.",
      "Add tinned tomatoes.",
      "Add water (you might need to judge how much to add by eye but you probably only need to add a tablespoon or two).",
      "Add salt and then leave to cook for 20 minutes until the tomato sauce reduces and becomes slightly jammy.",
    ],
  },
  {
    slug: "salad-shirazi",
    title: "Salad Shirazi",
    section: "mains",
    colour: "#56705C",
    intro:
      "Growing up, my mother had a rotation of Afghan dishes she would make on repeat. Amongst these were hearty and strongly flavoured dishes such as shola (Afghanistan’s version of a risotto) and pulao. These dishes were best paired with Afghan salata or a similar Iranian salad called salad shirazi. I have included the recipes for both so you can find which one you prefer. There is something that both of these salads have in common: they are bright, fresh, flavourful and will cut through hearty and heavy meals.",
    serves: "Four people",
    oven: "No cooking",
    ingredients: [
      "1 cucumber",
      "3 tomatoes",
      "1 red onion",
      "2 limes (juice of both, zest of one)",
      "2tsp dried mint",
      "3tbsp extra virgin olive oil",
      "Salt",
      "Pepper",
    ],
    notes: [
      {
        title: "Salata variation",
        items: ["Use lemons instead of lime", "No olive oil and no dried mint"],
      },
    ],
    method: [
      "Finely chop the cucumber into small squares.",
      "Finely chop the tomato. You can remove the inside of the tomato if you would like the salad to have more of a crunch (I usually snack on it while I am chopping).",
      "Finely chop half a red onion and add to your bowl.",
      "Zest the lime and then squeeze half of the juice out (if you don’t have a lime you can skip this step).",
      "Add olive oil, dried mint and salt and pepper to taste.",
    ],
  },
  {
    slug: "palak-paneer",
    title: "Palak Paneer",
    section: "mains",
    colour: "#4E7045",
    intro:
      "Never had paneer before? Oh you have not lived! High in protein and high in deliciousness, paneer is a satisfying thing to add to your meals instead of your regular chicken or tofu. The amount of spinach in this meal is great for boosting your iron intake too! If you are vegan you can sub the paneer with tofu in this recipe.",
    serves: "Six to seven people",
    oven: "Hob",
    ingredients: [
      "900g spinach",
      "450g paneer",
      "5 cloves garlic",
      "2 inch piece of ginger",
      "2-3 green chillies (optional)",
      "1 tbsp melted ghee (sub with any oil)",
      "2tsp cumin seeds",
      "50g butter",
      "1 tbsp garam masala",
      "2tsp salt",
      "2tbsp double cream",
    ],
    method: [
      "Fry the paneer in oil until golden brown. You will need to move around the paneer.",
      "Boil a kettle of water. Pour water into a pan or bowl that can handle hot water.",
      "Place the paneer in the bowl to soak. This keeps it soft for your curry.",
      "In a large pan heat your ghee and add cumin seeds. Then add ginger, garlic and chilli. After a minute or two add your spinach and allow it to cook for 4-5 minutes. Allow the spinach to cool a little.",
      "Add butter to the pan and using a stick blender, blend the spinach mixture until smooth and creamy.",
      "Drain the paneer, as you will be adding it to the sauce soon.",
      "Add garam masala and salt to the sauce and stir to combine. Check if the sauce has enough salt as spinach tends to need more salt than you expect!",
      "Add the paneer and simmer everything together for 5 minutes.",
    ],
  },
  {
    slug: "baba-ganoush",
    title: "Baba Ganoush",
    image: "images/baba-ganoush.jpg",
    section: "mains",
    colour: "#7A6A5C",
    intro:
      "During the summer, I fell in love with having this dip for breakfast. It is fairly simple to make, just put some aubergines in the oven and let them roast for around 40 minutes. Then mix in a few ingredients together and it’s ready to serve. I love to eat it with fresh bread, tortillas or any kind of flatbread I have on hand. Dressed up with some sumac and pine nuts it looks gorgeous but is the kind of dish that is happy letting the roasted aubergines shine.",
    serves: "Four people",
    oven: "180C / 200C / Gas Mark 4",
    time: "40 min roast",
    ingredients: [
      "3 aubergines",
      "2 cloves minced garlic",
      "¼ cup tahini",
      "Salt",
      "2tbsp olive oil",
      "1tbsp lemon juice",
      "1-2 tbsp finely chopped parsley (optional)",
      "Small handful of pine nuts (optional)",
      "2 tablespoons of yoghurt (optional)",
      "Sumac (optional)",
    ],
    method: [
      "Preheat oven to 180C / 200C / Gas Mark 4.",
      "Slice the aubergines in half and score the inside of the aubergines with a knife.",
      "Drizzle olive oil and sprinkle salt over the aubergines.",
      "Roast insides facing down for 40 minutes in an oven tray. While this is happening finely chop your garlic and get your lemons ready to squeeze.",
      "Once the aubergines are done (the insides will be soft) scoop them out into a bowl. Be careful as the aubergines will be quite hot. Allow them to cool down slightly if so.",
      "To your bowl, add the chopped garlic, olive oil, salt, tahini and parsley (if using).",
      "Taste and season to your liking.",
      "To make the baba ganoush lighter you can add yoghurt. Adding sumac will give the baba ganoush a bit more of a tang. You can drizzle pine nuts on top with extra olive oil to make it look pretty.",
    ],
  },
  {
    slug: "beetroot-and-walnut-dip",
    title: "Beetroot and Walnut Dip",
    image: "images/beetroot-and-walnut-dip.jpg",
    section: "mains",
    colour: "#8C2446",
    intro:
      "This beetroot hummus is great served with fresh bread. It also makes a great pasta sauce! Simply water down with pasta water and add to pasta.",
    serves: "Four to six people",
    oven: "180C Fan / 200C / Gas Mark 4",
    time: "5–7 min toasting",
    ingredients: [
      "200g beetroot (cooked)",
      "50g walnuts",
      "Olive oil",
      "1tbsp tahini or peanut butter",
      "1 large garlic clove",
      "1 lemon (or juice of)",
      "1tbsp cumin powder",
      "Salt",
      "Pepper",
      "Sumac (optional)",
    ],
    method: [
      "Preheat the oven to 180C fan/ 200C / Gas Mark 4.",
      "Place walnuts on a baking tray and toast for 5-7 minutes until their fragrance is released. Leave to cool.",
      "If you have a blender or food processor that can do this, blend the walnuts into fine crumbs.",
      "Then add the beetroot, tahini, olive oil, lemon juice, garlic, cumin and salt.",
      "Blend and taste to see if the dip is seasoned to your liking. Add more of any of the ingredients until you get the right balance of flavours.",
      "To serve you can top the dip with a drizzle of olive oil, sumac and chopped walnuts but this is optional.",
    ],
  },

  {
    slug: "beetroot-brownies",
    title: "Beetroot Brownies",
    image: "images/beetroot-brownies.jpg",
    section: "desserts",
    colour: "#8C2446",
    intro:
      "Okay you might be thinking, why would you put beetroot in a brownie? Now I think these brownies are amazing. They are a great way of adding some vegetables into your diet and the brownies are fudgy and cakey in texture. Absolutely divine.",
    serves: "Six to seven people",
    oven: "200C / 180C Fan / Gas Mark 6",
    time: "20 min bake",
    ingredients: [
      "100g vegetable oil",
      "275g cooked beetroot",
      "3 large eggs",
      "60g cocoa powder",
      "100g soft pitted dates",
      "100g self raising flour",
      "1tsp ground cinnamon",
      "1tsp bicarbonate of soda",
      "75g plain dark chocolate",
    ],
    method: [
      "Preheat the oven to 200C/ 180C Fan/ Gas Mark 6.",
      "Line a baking tin that is around 20 x 20cm with baking paper (or a tin of a similar or equivalent size).",
      "Place beetroot, eggs, cocoa powder, dates and oil in a blender and blend until thoroughly combined.",
      "Add the flour, cinnamon, a pinch of sea salt and bicarbonate of soda and blend until well combined.",
      "Stir in the chocolate then spoon into the tin.",
      "Bake for 20 minutes or until risen and just firm to the touch.",
      "Cool in the tin for 10 minutes then turn out and cut into squares to serve.",
    ],
  },
  {
    slug: "chocolate-mug-cake",
    title: "Chocolate Mug Cake",
    section: "desserts",
    colour: "#5A3A31",
    intro:
      "After busy days at uni, I would make a mug cake for myself in the evening and cosy up and eat this with some ice cream. With a show on in the background, this was a perfect little self care moment for me.",
    serves: "One",
    oven: "Microwave",
    time: "About 80 seconds",
    ingredients: [
      "3tbsp self raising flour",
      "3tbsp caster sugar (or maple syrup)",
      "1.5tbsp cocoa powder",
      "0.25tsp table salt",
      "0.25tsp baking powder",
      "4tbsp oat milk",
      "2tbsp vegetable oil (or olive oil)",
      "0.5tsp vanilla extract",
      "30g dark chocolate",
    ],
    method: [
      "Mix the dry ingredients together, then add the oat milk, vegetable oil and vanilla extract.",
      "Mix until smooth, place chocolate in the mixture and microwave for about 80 seconds.",
    ],
  },
  {
    slug: "raspberry-bakewell-cake",
    title: "Raspberry Bakewell Cake",
    section: "desserts",
    colour: "#C8677A",
    serves: "Six to seven people",
    oven: "180C / 160C Fan / Gas 4",
    time: "50 min bake",
    ingredients: [
      "140g ground almonds",
      "140g butter",
      "140g golden caster sugar",
      "140g self raising flour",
      "2 eggs",
      "1tsp vanilla extract",
      "250g raspberries",
      "2tsp flaked almonds (optional)",
      "Icing sugar to serve (optional)",
    ],
    method: [
      "Heat oven to 180C/160C fan/Gas 4.",
      "Base-line and grease a deep 20cm loose-bottomed cake tin or something of a similar size.",
      "Melt the butter in the microwave or in a pot. Then mix the ground almonds, butter, sugar, flour, eggs and vanilla extract until well combined.",
      "Spread half the mix over the cake tin and smooth over the top. Scatter the raspberries over, then dollop the remaining cake mixture on top and roughly spread. You might find this easier to do with your fingers. Scatter with flaked almonds and bake for 50 mins until golden.",
      "Cool, remove from the tin and dust with icing sugar to serve.",
    ],
  },
  {
    slug: "banana-bread",
    title: "Banana Bread",
    section: "desserts",
    colour: "#A8743A",
    serves: "Eight people (one loaf)",
    oven: "180C Fan / 200C / Gas Mark 6",
    time: "55–60 min bake",
    ingredients: [
      "2 large ripe bananas",
      "½ cup melted unsalted butter",
      "½ cup granulated sugar",
      "½ cup brown sugar",
      "2 large eggs",
      "1 teaspoon vanilla extract",
      "1½ cups plain flour",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 tsp cinnamon",
      "½ cup dark chocolate chips",
      "½ cup chopped walnuts (optional), and more for topping (optional)",
    ],
    method: [
      "Preheat oven to 180C Fan/ 200C / Gas Mark 6.",
      "Mash bananas and then add melted butter and eggs.",
      "Mix then add sugar, vanilla extract.",
      "Add flour, cinnamon, salt and baking soda.",
      "Fold in dark chocolate chips and walnuts if using.",
      "Pour batter into tin.",
      "Sprinkle more chocolate chips on top.",
      "Bake for 55 minutes to an hour, or until golden and a skewer inserted into the centre of the banana bread comes out mostly clean.",
    ],
  },
];

window.SECTIONS = [
  { id: "chai", label: "Chai", title: "To start, a cup of chai" },
  { id: "mains", label: "Mains", title: "Mains" },
  { id: "desserts", label: "Desserts", title: "Desserts" },
];

window.TIPS = {
  intro:
    "You don’t have to follow all of these tips but here are some things you could do to make your kitchen more sustainable. Some of these tips save you money and some require initial investment so see what fits your budget if you can.",
  items: [
    "Buy from zero waste stores where possible. At zero waste stores everything you buy doesn’t come in packaging, encouraging you to bring your own containers to refill (or often you will find containers there that you can use and take home). Zero waste stores stock everything from pasta, to grains, to oil and cheese. You can find almost everything you need here.",
    "Think about the packaging your food shop comes in. Could you buy your bananas loose instead of in plastic wrap?",
    "Use eco-friendly kitchen cleaning products (compostable sponges, refillable dish soap etc.)",
    "Buying locally sourced foods and food in season. Some fruits such as strawberries and blueberries are shipped in from the other side of the world to your supermarket when they aren’t in season in the UK. Opt for frozen fruit when this is the case or wait for the fruit to be back in season.",
    "Cut on plastic waste by using metal lunchbox containers, glass jars and beeswax wrap. Glass jars are great for storing food and can even be used for pickling if you are an eager home cook. Feel free to save jars that you collect with your grocery shop, if you think you can use them.",
    "Use Too Good To Go. This wonderful app allows you to tackle food waste and save money on food.",
    "Buying canned goods, pulses and grains will save you lots of money.",
    "I have also found that buying meat from butchers instead of the supermarket is much cheaper.",
    "Consider a veg or fruit box subscription. I did this as a student for some time, and it gave me access to organic fruit and vegetables. You could even ask around and see if anyone wouldn’t mind splitting the subscription with you.",
  ],
};
